### ISSUE TITLE
Bug: `/auth/profile` should not delete user profile's data if they were not provided

### ISSUE THREAD

**Issue by Deadreyo** [open-sauced/api.opensauced.pizza#108]
### Describe the bug

For the endpoint of `/auth/profile`, not providing data members in the request body would delete that value from the backend/database.
Ex: If I put an object without `bio` in the request (like just updating name, email, and timezone), it would delete the bio of the user.
This may cause a problem in onboarding when I only need to update the timezone of the user.

### Steps to reproduce

1. https://api.opensauced.pizza/#/
2. send a request to `/auth/profile` with `name`, `email` and another item.
3. all other missing items will be deleted in the user data.

### Affected services

api.opensauced.pizza

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by brandonroberts** [comment]
How is this a bug if those fields are not required? Its a valid request to send those fields as empty

**Comment by Deadreyo** [comment]
> How is this a bug if those fields are not required? Its a valid request to send those fields as empty

I don't mean sending the fields as empty strings, I mean not sending the fields.

For this body:
```
{
"name": "Ahmed",
"email": "ahmed@yahoo.com",
"timezone": "UTC-5"
}
```

now the user's bio, company, url, twitter, etc. are all deleted in the api.

**Comment by brandonroberts** [comment]
Closing as resolved
