### ISSUE TITLE
Bug: Can't vote for a repo even after removing my previous vote

### ISSUE THREAD

**Issue by diivi** [open-sauced/api.opensauced.pizza#122]
### Describe the bug

I get a 409 error when I vote for a repo I have already voted for earlier.
This is normal.
However, I also get a 409 error when I remove my vote for the repo and vote for it again.

### Steps to reproduce

1. Go to https://api.opensauced.pizza/
2. Enter auth token
3. Vote for a repo
4. Remove that vote
5. Vote for that repo again
6. error 409

### Affected services

api.opensauced.pizza

### Platforms

Desktop

### Browsers

Chrome

### Environment

Production

### Additional context

Was adding upvote/remove vote functionality to my opensauced-github extension when I faced this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by TAKANOME-DEV** [comment]
Thanks for opening this issue. Indeed you will get a `409` response even after deleting the vote in api.opensauced.pizza
I have tried it in the hot UI and it seems to be working.
Although I'm getting a `406` error the first time I vote any repos with the message:
```json
{
  "message": "JSON object requested, multiple (or no) rows returned",
  "details": "Results contain 0 rows, application/vnd.pgrst.object+json requires 1 row"
}
```

**Comment by 0-vortex** [comment]
Good catch, the soft delete function in https://github.com/open-sauced/api.opensauced.pizza/blob/91d62a1374bbb7fa9259cd75773d70f98dcb8a75/src/vote/repo-vote.controller.ts#L45 seems to have an edge case, will come back with more information upon investigation 🍕

**Comment by Anush008** [comment]
To add to this, I have observed that the bug persists even after manually removing the vote from the hot.opensauced.pizza dashboard.

**Comment by 0-vortex** [comment]
@open-sauced/maintainers anyone else with DB access can verify this? It would be a global bug across all our voting systems :/

**Comment by bdougie** [comment]
> @open-sauced/maintainers anyone else with DB access can verify this? It would be a global bug across all our voting systems

We need a better way to test and work with the API locally. No need to test this with live env. @diivi let's start with confirming are you able to run the API locally?

[Snaplet](https://www.snaplet.dev/) might provide a solution for mirroring data if that is needed. 

https://supabase.com/docs/guides/integrations/snaplet

**Comment by diivi** [comment]
> We need a better way to test and work with the API locally. No need to test this with live env. @diivi let's start with confirming are you able to run the API locally?

I tried a few weeks ago but need configuration files ( acc. to the project's README), then I had a discussion with vortex on discord where we decided I wouldn't need to set the project up locally.

I'll try again with a config file, if anyone could share one. @takanome-dev offered too.

**Comment by diivi** [comment]
I was able to set the project up, thanks to Brandon.  Can confirm that something is wrong with typeORM's softDelete here - https://github.com/open-sauced/api.opensauced.pizza/blob/91d62a1374bbb7fa9259cd75773d70f98dcb8a75/src/vote/vote.service.ts#L62.

I don't have much experience with TypeORM and NestJS but will have a look at it.
