### ISSUE TITLE
Feature: OpenAI endpoint for generating pr descriptions

### ISSUE THREAD

**Issue by bdougie** [open-sauced/api.opensauced.pizza#167]
### Type of feature

🍕 Feature

### Current behavior

Need to obscure an OpenAI token for this https://github.com/open-sauced/browser-extensions/pull/79

src/utils/aiprdescription/descriptionconfig.ts

### Suggested solution

POST - /v1/pull-request/description/generate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

**Comment by diivi** [comment]
Are we planning to remove the page for using your own OpenAI token in the extension then?

**Comment by bdougie** [comment]
> Are we planning to remove the page for using your own OpenAI token in the extension then?

Yes. User won't need to provide a token and OpenSauced will cover the cost. This will provide less friction in the experience.

**Comment by brandonroberts** [comment]
This endpoint is available in production through an authenticated route 

https://api.opensauced.pizza/#/Pull%20Requests%20service/generatePRDescription
