### ISSUE TITLE
Feature: implement logging system into console and typeorm

### ISSUE THREAD

**Issue by 0-vortex** [open-sauced/api.opensauced.pizza#17]
### Type of feature

🔥 Performance

### Current behavior

logging is done by `console.log` and we can inspect the containers in DO

### Suggested solution

Implement https://docs.nestjs.com/techniques/logger#using-the-logger-for-application-logging and potentially a custom logger

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by TAKANOME-DEV** [comment]
.take

**Comment by 0-vortex** [comment]
> .take

Hey this was actually already implemented :D
