### ISSUE TITLE
Bug: No contributions data return for a 30 days range

### ISSUE THREAD

**Issue by takanome-dev** [open-sauced/api.opensauced.pizza#181]
It seems there is a problem because this route does not show anything, While I am sure I have at least one merged PR that I made this month.

https://api.opensauced.pizza/v1/users/BaseMax/prs?limit=15&range=30

_Originally posted by @BaseMax in https://github.com/open-sauced/insights/issues/865#issuecomment-1585525639_

**Comment by babblebey** [comment]
Hey @takanome-dev 

Take my own login to the query

https://api.opensauced.pizza/v1/users/babblebey/prs?limit=15&range=30

Everything seem to look normal to me, or is there some specifics that I'm missing out on?

**Comment by takanome-dev** [comment]
No, it's working fine. I wonder why there is no data for him.

Closing this for now.

**Comment by babblebey** [comment]
> No, it's working fine. I wonder why there is no data for him.
> 
> Closing this for now. 

Oh @takanome-dev 

That is pretty much because "BaseMax" GitHub seem kinda empty
