### ISSUE TITLE
Status Page

### ISSUE THREAD

**Issue by bdougie** [open-sauced/api.opensauced.pizza#28]
With the new footer, we should put together a status page for this API and potentially for the gs-api. This footer will get added to all sites. 

<img width="524" alt="Screen Shot 2022-09-15 at 6 40 36 PM" src="https://user-images.githubusercontent.com/5713670/190538237-64149c03-be7f-4b67-8f2e-c86cff777965.png">

**Comment by bdougie** [comment]
Realize we already have a health service built into swagger. Linking to [this](https://api.opensauced.pizza/docs#/Health%20check%20service/healthStatusService) in a static page would be the quick fix.

**Comment by 0-vortex** [comment]
> Realize we already have a health service built into swagger. Linking to [this](https://api.opensauced.pizza/docs#/Health%20check%20service/healthStatusService) in a static page would be the quick fix. 

We have quite a bit of data there, hard disk, memory and endpoints health 🫡

**Comment by Deadreyo** [comment]
@bdougie @0-vortex The link leads to 404

**Comment by bdougie** [comment]
Yeah, url no longer needs /docs

**Comment by Deadreyo** [comment]
So basically a solution would be to make the api service has a new endpoint that returns a static site that loads data from the existing health endpoint?

**Comment by 0-vortex** [comment]
> So basically a solution would be to make the api service has a new endpoint that returns a static site that loads and shows data from the existing health endpoint?

I've investigated solutions like what you mentioned, a nice example would be https://www.npmjs.com/package/nestjs-status-monitor - however they opinionate the static distribution of the API which is already bulky (swagger-ui); in production we would not have any http requests outside of the API routes, so we should create this status page in the client repo (hot?) 🍕

**Comment by Deadreyo** [comment]
> > So basically a solution would be to make the api service has a new endpoint that returns a static site that loads and shows data from the existing health endpoint?
> 
> I've investigated solutions like what you mentioned, a nice example would be https://www.npmjs.com/package/nestjs-status-monitor - however they opinionate the static distribution of the API which is already bulky (swagger-ui); in production we would not have any http requests outside of the API routes, so we should create this status page in the client repo (hot?) 🍕

@bdougie mentioned that the footer would be in all sites, so this means this new page in the client repo would have to be duplicated in every project, doesnt it?

**Comment by bdougie** [comment]
Not necessarily. It would be ideal to make this a new standalone static page that talks to the api. If all of open sauced is down the status page should still be.

Potentially status.opensauced.pizza or even saucedstatus.com

Step 1 would be build a static site that points to the health endpoint.

**Comment by bdougie** [comment]
Put together some mocks of what status.opensauced.pizza could be. I suggest using a tool like [Astro](https://astro.build/) to create a quick landing page, but basic HTML also works. We can create a new repo when ready.

![Screen Shot 2022-10-13 at 9 22 05 AM](https://user-images.githubusercontent.com/5713670/195652011-66edc130-560f-4676-88f0-5b0bab96e31d.png)


![Screen Shot 2022-10-13 at 9 22 11 AM](https://user-images.githubusercontent.com/5713670/195651991-6310b74c-8fd2-4455-a2ee-115829b87af4.png)

**Comment by Deadreyo** [comment]
This was solved in the new repo: https://github.com/open-sauced/status.opensauced.pizza
