### ISSUE TITLE
Feature: document how to get your bearer token

### ISSUE THREAD

**Issue by bdougie** [open-sauced/api.opensauced.pizza#48]
### Type of feature

📝 Documentation

### Current behavior

To make POST requests in the swagger playground, you need a JWT. 

### Suggested solution

I know there is a path to get it from your network tab in the hot UI, but we would want to document that or make it easier to find

![Screen Shot 2022-10-04 at 2 59 48 PM](https://user-images.githubusercontent.com/5713670/193938434-708de48f-f3f4-4804-aac2-10836db40212.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by bdougie** [comment]
I went back look at the stream on how to do this. Let me know if there is a better way we can generate a token. Perhaps connect supabase auth to the swagger UI?

## Steps to get a bearer token for local API testing
1. Run the open-sauced/hot repo on localhost
2. console.log(currentUser?.access_token) [here](https://github.com/open-sauced/hot/blob/beta/src/hooks/useSupabaseAuth.ts#L11).
3. Copy the token from the console
4. place in the api swagger UI

Here is a clip of me doing it on stream last month. Apologies for the rambling in between. 

https://www.twitch.tv/videos/1610549636

**Comment by 0-vortex** [comment]
handled by browser extensions
